"""Composable stateful agents with tool handlers and MCP integration."""

from simagentplg.agent.base import BaseAgent
from simagentplg.agent.cancellation import (
    AgentCancelledError,
    CancellationSource,
    CancellationToken,
)
from simagentplg.agent.compaction import (
    CompactionRequest,
    CompactionResult,
    CompactionRuntime,
    CompactionStatus,
    CompactionTrigger,
    Compactor,
    CompactorOutput,
    SummaryEntry,
)
from simagentplg.agent.context_builder import AgentContextBuilder, ContextBuildResult
from simagentplg.agent.context_management import (
    AutoCompactionPolicy,
    CompactionDecision,
    CompactionDecisionReason,
    CompactionPolicy,
    CompactionPreparation,
    ContextBudget,
    ContextUsageEstimate,
    ContextUsageSource,
    HeuristicMessageTokenEstimator,
    MessageTokenEstimator,
    estimate_context_usage,
    prepare_compaction,
)
from simagentplg.agent.events import (
    AgentEvent,
    AgentEventKind,
    AgentEventPayload,
    AgentEventSink,
    AgentEventSinkError,
    AgentFinished,
    AgentStarted,
    AssistantTextDelta,
    AssistantThinkingDelta,
    CompactionCompleted,
    CompactionFailed,
    CompactionStarted,
    CompositeAgentEventSink,
    ContextPressureEvaluated,
    MessageCompleted,
    ToolCompleted,
    ToolProgressed,
    ToolStarted,
    TurnCompleted,
    TurnStarted,
)
from simagentplg.agent.model_compactor import (
    CompactionContextBuilder,
    ModelCompactor,
)
from simagentplg.agent.orchestrator import AgentOrchestrator
from simagentplg.agent.result import (
    AgentRunError,
    AgentRunResult,
    RunStatus,
    StopReason,
)
from simagentplg.agent.runtime_policy import RuntimePolicy
from simagentplg.agent.state import AgentState, AgentStatus
from simagentplg.agent.types import (
    StepOutcome,
    ToolCallResult,
    ToolControl,
    ToolProgressReporter,
    ToolProgressUpdate,
)
from simagentplg.agent.usage import RunUsage
from simagentplg.handlers import (
    BaseHandler,
    McpToolHandler,
    MethodToolHandler,
    ToolDefinitionError,
    UnknownToolError,
)
from simagentplg.middleware import (
    Middleware,
    ToolCallContext,
    ToolMiddleware,
    ToolNext,
    compose_tool_middlewares,
    format_tool_call_preview,
)
from simagentplg.plugins.mcp.mcp_manager import McpServerManager
from simagentplg.plugins.skill.skill_manager import SkillManager
from simagentplg.providers import (
    AssistantMessage,
    ContextOverflowError,
    ModelAdapter,
    ModelAuthenticationError,
    ModelConfig,
    ModelErrorKind,
    ModelProviderError,
    ModelRateLimitError,
    ModelResponseCompleted,
    ModelStreamEvent,
    ModelTextDelta,
    ModelThinkingDelta,
    ModelTimeoutError,
    ModelToolCall,
    ModelUsage,
    OpenAIModelAdapter,
)
from simagentplg.session import (
    SESSION_SCHEMA_VERSION,
    AgentSession,
    JsonFileSessionStorage,
    MemorySessionStorage,
    SessionCompaction,
    SessionError,
    SessionMessage,
    SessionRecorder,
    SessionRun,
    SessionSerializationError,
    SessionStorage,
    SessionStorageError,
    session_from_dict,
    session_to_dict,
)

__all__ = [
    "BaseAgent",
    "AgentCancelledError",
    "CancellationSource",
    "CancellationToken",
    "Compactor",
    "CompactorOutput",
    "CompactionRequest",
    "CompactionResult",
    "CompactionRuntime",
    "CompactionStatus",
    "CompactionTrigger",
    "SummaryEntry",
    "CompactionContextBuilder",
    "ModelCompactor",
    "ModelConfig",
    "ModelAdapter",
    "OpenAIModelAdapter",
    "AssistantMessage",
    "ModelErrorKind",
    "ModelProviderError",
    "ContextOverflowError",
    "ModelRateLimitError",
    "ModelTimeoutError",
    "ModelAuthenticationError",
    "ModelStreamEvent",
    "ModelTextDelta",
    "ModelThinkingDelta",
    "ModelResponseCompleted",
    "ModelToolCall",
    "ModelUsage",
    "AgentState",
    "AgentStatus",
    "AgentContextBuilder",
    "ContextBuildResult",
    "ContextBudget",
    "ContextUsageEstimate",
    "ContextUsageSource",
    "MessageTokenEstimator",
    "HeuristicMessageTokenEstimator",
    "CompactionPolicy",
    "AutoCompactionPolicy",
    "CompactionDecision",
    "CompactionDecisionReason",
    "CompactionPreparation",
    "estimate_context_usage",
    "prepare_compaction",
    "AgentEvent",
    "AgentEventKind",
    "AgentEventPayload",
    "AgentEventSink",
    "AgentEventSinkError",
    "CompositeAgentEventSink",
    "CompactionStarted",
    "CompactionCompleted",
    "CompactionFailed",
    "ContextPressureEvaluated",
    "AgentStarted",
    "AssistantThinkingDelta",
    "AssistantTextDelta",
    "TurnStarted",
    "MessageCompleted",
    "ToolStarted",
    "ToolProgressed",
    "ToolCompleted",
    "TurnCompleted",
    "AgentFinished",
    "AgentOrchestrator",
    "RuntimePolicy",
    "AgentRunResult",
    "AgentRunError",
    "RunStatus",
    "StopReason",
    "RunUsage",
    "StepOutcome",
    "ToolCallResult",
    "ToolControl",
    "ToolProgressReporter",
    "ToolProgressUpdate",
    "Middleware",
    "ToolMiddleware",
    "ToolCallContext",
    "ToolNext",
    "compose_tool_middlewares",
    "format_tool_call_preview",
    "BaseHandler",
    "MethodToolHandler",
    "McpToolHandler",
    "ToolDefinitionError",
    "UnknownToolError",
    "McpServerManager",
    "SkillManager",
    "AgentSession",
    "SessionMessage",
    "SessionRun",
    "SessionCompaction",
    "SessionStorage",
    "JsonFileSessionStorage",
    "MemorySessionStorage",
    "SessionRecorder",
    "SESSION_SCHEMA_VERSION",
    "session_to_dict",
    "session_from_dict",
    "SessionError",
    "SessionSerializationError",
    "SessionStorageError",
]
